package dto

type CoreConfigProxy struct {
	AnonymousMode           bool   `json:"anonymous_mode,omitempty"`
	ForceProxy              bool   `json:"force_proxy,omitempty"`
	Hostname                string `json:"hostname,omitempty"`
	Password                string `json:"password,omitempty"`
	Port                    int    `json:"port,omitempty"`
	ProxyHostnames          bool   `json:"proxy_hostnames,omitempty"`
	ProxyPeerConnections    bool   `json:"proxy_peer_connections,omitempty"`
	ProxyTrackerConnections bool   `json:"proxy_tracker_connections,omitempty"`
	Type                    int    `json:"type,omitempty"`
	Username                string `json:"username,omitempty"`
}

type CoreConfigResponse struct {
	SendInfo                                bool             `json:"send_info,omitempty"`
	InfoSent                                float64          `json:"info_sent,omitempty"`
	DaemonPort                              int              `json:"daemon_port,omitempty"`
	AllowRemote                             bool             `json:"allow_remote,omitempty"`
	PreAllocateStorage                      bool             `json:"pre_allocate_storage,omitempty"`
	DownloadLocation                        string           `json:"download_location,omitempty"`
	ListenPorts                             []int            `json:"listen_ports,omitempty"`
	ListenInterface                         string           `json:"listen_interface,omitempty"`
	OutgoingInterface                       string           `json:"outgoing_interface,omitempty"`
	RandomPort                              bool             `json:"random_port,omitempty"`
	ListenRandomPort                        *bool            `json:"listen_random_port,omitempty"`
	ListenUseSysPort                        bool             `json:"listen_use_sys_port,omitempty"`
	ListenReusePort                         bool             `json:"listen_reuse_port,omitempty"`
	OutgoingPorts                           []int            `json:"outgoing_ports,omitempty"`
	RandomOutgoingPorts                     bool             `json:"random_outgoing_ports,omitempty"`
	CopyTorrentFile                         bool             `json:"copy_torrent_file,omitempty"`
	DelCopyTorrentFile                      bool             `json:"del_copy_torrent_file,omitempty"`
	TorrentfilesLocation                    string           `json:"torrentfiles_location,omitempty"`
	PluginsLocation                         string           `json:"plugins_location,omitempty"`
	PrioritizeFirstLastPieces               bool             `json:"prioritize_first_last_pieces,omitempty"`
	SequentialDownload                      bool             `json:"sequential_download,omitempty"`
	Dht                                     bool             `json:"dht,omitempty"`
	Upnp                                    bool             `json:"upnp,omitempty"`
	Natpmp                                  bool             `json:"natpmp,omitempty"`
	Utpex                                   bool             `json:"utpex,omitempty"`
	Lsd                                     bool             `json:"lsd,omitempty"`
	EncInPolicy                             int              `json:"enc_in_policy,omitempty"`
	EncOutPolicy                            int              `json:"enc_out_policy,omitempty"`
	EncLevel                                int              `json:"enc_level,omitempty"`
	MaxConnectionsGlobal                    int              `json:"max_connections_global,omitempty"`
	MaxUploadSpeed                          float64          `json:"max_upload_speed,omitempty"`
	MaxDownloadSpeed                        float64          `json:"max_download_speed,omitempty"`
	MaxUploadSlotsGlobal                    int              `json:"max_upload_slots_global,omitempty"`
	MaxHalfOpenConnections                  int              `json:"max_half_open_connections,omitempty"`
	MaxConnectionsPerSecond                 int              `json:"max_connections_per_second,omitempty"`
	IgnoreLimitsOnLocalNetwork              bool             `json:"ignore_limits_on_local_network,omitempty"`
	MaxConnectionsPerTorrent                int              `json:"max_connections_per_torrent,omitempty"`
	MaxUploadSlotsPerTorrent                int              `json:"max_upload_slots_per_torrent,omitempty"`
	MaxUploadSpeedPerTorrent                int              `json:"max_upload_speed_per_torrent,omitempty"`
	MaxDownloadSpeedPerTorrent              int              `json:"max_download_speed_per_torrent,omitempty"`
	EnabledPlugins                          []string         `json:"enabled_plugins,omitempty"`
	AddPaused                               bool             `json:"add_paused,omitempty"`
	MaxActiveSeeding                        int              `json:"max_active_seeding,omitempty"`
	MaxActiveDownloading                    int              `json:"max_active_downloading,omitempty"`
	MaxActiveLimit                          int              `json:"max_active_limit,omitempty"`
	DontCountSlowTorrents                   bool             `json:"dont_count_slow_torrents,omitempty"`
	QueueNewToTop                           bool             `json:"queue_new_to_top,omitempty"`
	StopSeedAtRatio                         bool             `json:"stop_seed_at_ratio,omitempty"`
	RemoveSeedAtRatio                       bool             `json:"remove_seed_at_ratio,omitempty"`
	StopSeedRatio                           float64          `json:"stop_seed_ratio,omitempty"`
	ShareRatioLimit                         float64          `json:"share_ratio_limit,omitempty"`
	SeedTimeRatioLimit                      float64          `json:"seed_time_ratio_limit,omitempty"`
	SeedTimeLimit                           int              `json:"seed_time_limit,omitempty"`
	AutoManaged                             bool             `json:"auto_managed,omitempty"`
	MoveCompleted                           bool             `json:"move_completed,omitempty"`
	MoveCompletedPath                       string           `json:"move_completed_path,omitempty"`
	MoveCompletedPathsList                  []string         `json:"move_completed_paths_list,omitempty"`
	DownloadLocationPathsList               []string         `json:"download_location_paths_list,omitempty"`
	PathChooserShowChooserButtonOnLocalhost bool             `json:"path_chooser_show_chooser_button_on_localhost,omitempty"`
	PathChooserAutoCompleteEnabled          bool             `json:"path_chooser_auto_complete_enabled,omitempty"`
	PathChooserAcceleratorString            string           `json:"path_chooser_accelerator_string,omitempty"`
	PathChooserMaxPopupRows                 int              `json:"path_chooser_max_popup_rows,omitempty"`
	PathChooserShowHiddenFiles              bool             `json:"path_chooser_show_hidden_files,omitempty"`
	NewReleaseCheck                         bool             `json:"new_release_check,omitempty"`
	Proxy                                   *CoreConfigProxy `json:"proxy,omitempty"`
	PeerTos                                 string           `json:"peer_tos,omitempty"`
	RateLimitIpOverhead                     bool             `json:"rate_limit_ip_overhead,omitempty"`
	GeoipDbLocation                         string           `json:"geoip_db_location,omitempty"`
	CacheSize                               int              `json:"cache_size,omitempty"`
	CacheExpiry                             int              `json:"cache_expiry,omitempty"`
	AutoManagePreferSeeds                   bool             `json:"auto_manage_prefer_seeds,omitempty"`
	Shared                                  bool             `json:"shared,omitempty"`
	SuperSeeding                            bool             `json:"super_seeding,omitempty"`
}
